# Generated by Django 3.2.6 on 2021-08-09 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artists',
            new_name='artist',
        ),
    ]
